### ISSUE TITLE
After messages are duplicated

### ISSUE THREAD

**Issue by MythicalRollers** [ironmonk88/monks-chat-timer#6] opened 2023-03-27 13:37 UTC
When creating a time with an after message, the after message will populate a number of times equal to the number of signed in users.
Chat code I am using:
/timer -1:00 Battle Planning Minute! (Minute's up suckers, time to die!)
![After Message](https://user-images.githubusercontent.com/106455111/227954594-3022d03e-59a9-447c-b033-faaede1c849f.png)

**Comment by ironmonk108** [comment] 2023-03-28 17:58
Technically a duplicate of #4, but you provided better information.

**Comment by ironmonk108** [comment] 2023-06-13 01:14
Closing as this should have been cleared with the last release

**Closed as completed by ironmonk108** 2023-06-13 01:14 UTC
Labels: duplicate, Fixed waiting for release
